apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
        - name: lab
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
            - name: REACT_APP_USERNAME
              value: anyapp
            - name: REACT_APP_COMPANY_NAME
              value: anycompany
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: lab
spec:
  selector:
    app: lab
  ports:
    - port: 3000
      targetPort: 3000
